export const allProducts = [
  {
    id: 1,
    title: "Tikvice",
    category: "Povrće",
    company: "Proizvođač 1",
    organic: true,
    region: "Beogard",
    price: "200",
    currency: "din",
  },
  {
    id: 2,
    title: "Jabuke",
    category: "Voće",
    company: "Proizvođač 2",
    organic: false,
    region: "Novi Sad",
    price: "150",
    currency: "din",
  },
  {
    id: 3,
    title: "Mleko i mlečni proizvodi",
    category: "Mlečni proizvodi",
    company: "Proizvođač 3",
    organic: true,
    region: "Kragujevac",
    price: "300",
    currency: "din",
  },
  {
    id: 4,
    title: "Meso i riba",
    category: "Meso i riba",
    company: "Proizvođač 4",
    organic: false,
    region: "Niš",
    price: "500",
    currency: "din",
  },
  {
    id: 5,
    title: "Hleb i peciva",
    category: "Hleb i peciva",
    company: "Proizvođač 5",
    organic: true,
    region: "Subotica",
    price: "100",
    currency: "din",
  },
  {
    id: 6,
    title: "Piće",
    category: "Piće",
    company: "Proizvođač 6",
    organic: false,
    region: "Zrenjanin",
    price: "80",
    currency: "din",
  },
  {
    id: 7,
    title: "Slatkiši",
    category: "Slatkiši",
    company: "Proizvođač 7",
    organic: true,
    region: "Kruševac",
    price: "250",
    currency: "din",
  },
  {
    id: 8,
    title: "Ostalo",
    category: "Ostalo",
    company: "Proizvođač 8",
    organic: false,
    region: "Užice",
    price: "120",
    currency: "din",
  },
];